baseurl: /algo-notes-ci
markdown: kramdown
kramdown:
  input: GFM       # GitHub Flavored Markdown
  hard_wrap: true  # 改行を <br> に変換
exclude:
  - assets/style.css      # 圧縮済みのファイルを除外
  - index.html
  - main.js
